# Graph Convolutional Networks Basics

<img src="./PictureSources/0.PNG" width=300px align="left"></img>

In [28]:
import numpy as np

# 1: 有被指，0: 沒有被指
graph = np.matrix(
    [[0, 0, 0, 1],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 1, 0, 0]],
    dtype = float
)

print("graph relations\n", graph)

feature = np.matrix([[i, -i] for i in range(graph.shape[0])], dtype=float)

print("\nfeature matrix\n", feature)
print("\noutput\n", graph * feature)

# 這個矩陣乘法代表了對於每個節點來說，它們的值代表了每個指向該節點的節點們的特徵總和。
# 舉例而言，節點 1 的值[ 2., -2.]，即為指向它的節點 0與節點 2 加總而得([ 0., 0.] + [ 2., -2.])。
# 這邊可以自己算算看會更有感覺。

I = np.matrix(np.eye(graph .shape[0]))
# graph relation matrix with self-added
graph_hat = graph + I
print("\ngraph relation hat\n", graph_hat)

D = np.array(np.sum(graph_hat, axis=1)).reshape(-1)
D = np.matrix(np.diag(D))
print("\nD\n", D)

print("\nresult\n", (D ** -1) * graph_hat)

graph relations
 [[0. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]

feature matrix
 [[ 0.  0.]
 [ 1. -1.]
 [ 2. -2.]
 [ 3. -3.]]

output
 [[ 3. -3.]
 [ 2. -2.]
 [ 4. -4.]
 [ 1. -1.]]

graph relation hat
 [[1. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 1. 0. 1.]]

D
 [[2. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 2.]]

result
 [[0.5        0.         0.         0.5       ]
 [0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.         0.5        0.         0.5       ]]


# Basic GCN Model

In [10]:
from networkx import *
import numpy as np

zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
# print(order)
A = to_numpy_matrix(zkc, nodelist=order)
I = np.eye(zkc.number_of_nodes())

A_hat = A + I # 有自循環的相鄰矩陣
D_hat = np.array(np.sum(A_hat, 1)).reshape(-1)
D_hat = np.matrix(np.diag(D_hat))

In [17]:
'''
dataset website:
http://konect.cc/networks/ucidata-zachary/
http://vlado.fmf.uni-lj.si/pub/networks/data/ucinet/ucidata.htm#zachary
http://vlado.fmf.uni-lj.si/pub/networks/data/ucinet/zachary.dat
'''

(34, 34)
