# Ch2.0 NumPy Basics

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.__version__

'1.16.2'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [2]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

NameError: name 'np' is not defined

In [9]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [10]:
ar1

array([0, 1, 2, 3])

In [11]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [12]:
#ar2.shape
ar2.shape

(2, 3)

In [13]:
#ar2.ndim
ar2.ndim

2

In [15]:
# Numbers of Element within np array
print(ar1.size)
print(ar2.size)

4
6


In [20]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [19]:
ar3 = np.array([[0,3,5],[1,2,3,4]])
ar3 # is not an array anymore

array([list([0, 3, 5]), list([1, 2, 3, 4])], dtype=object)

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [21]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

array([3, 6, 9])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [24]:
# args - start element,end element, number of elements
#ar5=np.linspace(0,2.0/3,4); ar5
ar5=np.linspace(0,2.0/3,4)
ar5

array([0.        , 0.22222222, 0.44444444, 0.66666667])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [26]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.zeros

In [27]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.eye

In [28]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [29]:
# Create diagonal array
ar10=np.diag((2,1,4,6)); ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [30]:
# Using the rand, randn functions
# rand(m) produces uniformly distributed random numbers with range 0 to m
np.random.seed(200) # Set seed
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [34]:
np.random.seed(200)
np.random.random(3)

array([0.94763226, 0.22654742, 0.59442014])

In [17]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

### numpy.empty

In [53]:
ar13=np.empty((3,2)); ar13

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [58]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

array([ 2., -1.,  6.,  3.])

In [59]:
ar.dtype

dtype('float64')

In [60]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int32')

In [64]:
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [66]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

dtype('<U9')

In [77]:
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [78]:
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [79]:
# 無條件捨去
f_ar.astype(int)

array([ 3, -2,  8])

## NumPy indexing and slicing

In [5]:
# print entire array, element 0, element 1, last element.
ar = np.arange(5); print(ar); ar[0], ar[1], ar[-1]

[0 1 2 3 4]


(0, 1, 4)

In [6]:
# 2nd, last and 1st elements
ar=np.arange(5); ar[1], ar[-1], ar[0]

(1, 4, 0)

In [7]:
# Reverse array using ::-1 idiom
ar=np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [8]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [9]:
ar[1,1]

8

In [10]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [11]:
# Retrieve row 2
ar[2]

array([11, 12, 13])

In [12]:
ar[2,:]

array([11, 12, 13])

In [13]:
# Retrieve column 1
ar[:,1]

array([ 3,  5, 12])

### Fancy Indexing

In [9]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [23]:
# access three different elements
print([x[3], x[7], x[2]])
print(type(x))

[71, 86, 14]
<class 'numpy.ndarray'>


In [26]:
# pass a single list or array of indices to obtain the same result
ind = [3, 7, 2]
print(x[ind])
print(type(x))

[71 86 14]
<class 'numpy.ndarray'>


In [29]:
print(x[[3,7,2]])
print(type(x))

[71 86 14]
<class 'numpy.ndarray'>


##  Array slicing
Arrays can be sliced using the following syntax:<br>
ar[startIndex: endIndex: stepValue].

In [48]:
print(np.arange(6))
ar=2*np.arange(6); print(ar)

[0 1 2 3 4 5]
[ 0  2  4  6  8 10]


In [37]:
ar[1:5:2]

array([2, 6])

In [38]:
# if we wish to include the endIndex value, we need to go above it
ar[1:6:2] 

array([ 2,  6, 10])

In [39]:
ar[:4]

array([0, 2, 4, 6])

In [40]:
ar[4:]

array([ 8, 10])

In [41]:
# Slice array with stepValue=3
ar[::3]

array([0, 6])

Assignment and slicing can be combined as shown in the following code snippet:

In [47]:
ar

array([1, 1, 1, 1, 1, 1])

In [50]:
ar[:3]=1; ar

array([1, 1, 1, 1, 1, 1])

In [51]:
ar[2:]=np.ones(4);ar

array([1, 1, 1, 1, 1, 1])

## Array masking

In [10]:
import numpy as np
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [12]:
ar % 2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [3]:
evenMask=(ar % 2==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [13]:
# Fancy Index
evenNums=ar[evenMask]; evenNums

array([ 4,  0, 16,  8,  0])

To eliminate missing values

In [22]:
ar=np.array(['Hungary','Nigeria',
'Guatemala','','Poland','','Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [23]:
ar==''

array([False, False, False,  True, False,  True, False])

In [24]:
ar[ar=='']='USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

In [25]:
# Only documented the first 9 characters (Because of the length of 'Guatemala')
ar[ar=='Japan']='Republic of China'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA',
       'Republic '], dtype='<U9')

## Copies and views

<b>Modifying view modifies original array</b>

In [26]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [28]:
ar2[1]=-1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
ar2

array([ 0, -1,  4,  6,  8, 10])

<b>Use np.copy to force a copy</b><br>

In [31]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
arc=ar[:3].copy(); arc

array([0, 1, 2])

In [33]:
arc[0]=-1; arc

array([-1,  1,  2])

In [34]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])