# Ch2.1 NumPy Operations

# Operations

## Basic Operations

In [2]:
import numpy as np
import pandas as pd

In [3]:
ar=np.arange(0,7)*5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [4]:
ar=np.arange(5) ** 4 ; ar

array([  0,   1,  16,  81, 256], dtype=int32)

In [5]:
ar ** 0.5

array([ 0.,  1.,  4.,  9., 16.])

In [6]:
ar=3+np.arange(0, 30,3); ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
ar2=np.arange(1,11); ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
ar+ar2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [9]:
ar-ar2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
ar/ar2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [11]:
ar*ar2

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

<b>Array multiplication is element wise</b><br>

In [12]:
ar=np.array([[1,1],[1,1]]); ar

array([[1, 1],
       [1, 1]])

In [13]:
ar2=np.array([[2,2],[2,2]]); ar2

array([[2, 2],
       [2, 2]])

In [15]:
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [16]:
ar*ar2

array([[2, 2],
       [2, 2]])

<b>Comparison and logical operations are also elememt-wise</b>

In [17]:
ar=np.arange(1,5); ar

array([1, 2, 3, 4])

In [18]:
ar2=np.arange(5,1,-1); ar2

array([5, 4, 3, 2])

In [19]:
ar < ar2

array([ True,  True, False, False])

In [26]:
l1 = np.array([True,False,True,False])
l2 = np.array([False,False,True, False])
np.logical_and(l1,l2)

array([False, False,  True, False])

<b>For element-wise operations, the 2 arrays must be the same shape else an error results</b>

In [27]:
ar=np.arange(0,6); ar

array([0, 1, 2, 3, 4, 5])

In [28]:
ar2=np.arange(0,8); ar2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
ar*ar2

ValueError: operands could not be broadcast together with shapes (6,) (8,) 

<b>NumPy arrays can be transposed</b>

In [30]:
ar=np.array([[1,2,3],[4,5,6]]); ar

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
ar.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Reduction Operations
Operators such as np.sum and np.prod perform reduces on arrays; that is, they
combine several elements into a single value:

In [34]:
ar=np.arange(1,5)
print(ar)
print(ar.prod())

[1 2 3 4]
24


specify whether the reduction operator to be applied row-wise or column-wise

In [41]:
ar=np.array([np.arange(1,6),np.arange(1,6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [42]:
ar.prod() # 1*2*3*4*5*1*2*3*4*5

14400

In [46]:
#Columns
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [45]:
#Rows
np.prod(ar,axis=1)

array([120, 120])

not specifying an axis results in the operation being applied to all elements of the array

In [47]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]); ar.sum()

54

In [51]:
print(ar.sum(axis=0))
print(ar.sum(axis=1))

[15 18 21]
[ 9 18 27]


In [52]:
print(ar.mean())
print(ar.mean(axis=0))
print(ar.mean(axis=1))

6.0
[5. 6. 7.]
[3. 6. 9.]


In [54]:
print(np.median(ar))
print(np.median(ar, axis=0))
print(np.median(ar, axis=1))

6.0
[5. 6. 7.]
[3. 6. 9.]


## Statistical operators

In [55]:
np.random.seed(10)
ar=np.random.randint(0,10, size=(4,5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [57]:
print(ar.mean())
print(ar.mean(axis=0))
print(ar.mean(axis=1))

4.45
[5.25 4.25 5.   3.5  4.25]
[4.6 3.6 4.2 5.4]


In [58]:
print(ar.std())
print(ar.std(axis=0))
print(ar.std(axis=1))

3.427462618322773
[3.56195171 2.04633819 3.31662479 3.27871926 4.26468053]
[3.82622529 4.02988834 2.71293199 2.65329983]


In [59]:
ar.var(axis=0) #across rows

array([12.6875,  4.1875, 11.    , 10.75  , 18.1875])

## Logical operators

In [60]:
np.random.seed(100)
ar=np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [61]:
np.any((ar%7)==0)

False

In [ ]:
np.all(ar<11)

## Broadcasting

In [62]:
ar=np.ones([3,2]); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
ar2=np.array([2,3]); ar2

array([2, 3])

In [64]:
ar+ar2

array([[3., 4.],
       [3., 4.],
       [3., 4.]])